name: Ubuntu

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: submodules-init
      uses: snickerbockers/submodules-init@v4
    - name: install dependencies
      run: sudo apt install libsdl2-dev
    - name: run-cmakeix Makefiles, VS16Win64
      uses: lukka/run-cmake@v2.5
      with:
        cmakeGenerator: UnixMakefiles
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
